name = "genremnant-d1-api"
main = "src/index.js"
compatibility_date = "2025-12-15"

account_id = "912a82900111b3b5e4ac9082c967bff0"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "mygenremnant"
database_id = "3335f624-58cb-44c3-a344-dd0bf9dc17d9"
